const cadastrarApartamentoRoutes = require('./scripts/cadastrar_apartamento_routes');
app.use('/api/apartamentos', cadastrarApartamentoRoutes);
const cadastrarManutencaoRoutes = require('./scripts/cadastrar_manutencao_routes');
app.use('/api/manutencoes', cadastrarManutencaoRoutes);
const cadastrarMoradorRoutes = require('./scripts/cadastrar_morador_routes');
app.use('/api/moradores', cadastrarMoradorRoutes);
const manterBlocosRoutes = require('./scripts/manter_blocos_routes');
app.use('/api/blocos', manterBlocosRoutes);
const pesquisarApartamentosRoutes = require('./scripts/pesquisar_apartamentos_routes');
app.use('/api/apartamentos', pesquisarApartamentosRoutes);
const pesquisarBlocosRoutes = require('./scripts/pesquisar_blocos_routes');
app.use('/api/blocos', pesquisarBlocosRoutes);
